---
title: "ST 661 Note"
author: "Frances Lin"
date: "1/18/2022"
output: pdf_document
---

## Outline 

- Eigenvalue, eigvenvector, eigenspace 

- Idempotent matrix 

## Last time 

Whenever we have 2 eigenvalues, we would like to find eigenvalues s.t. they are perpendicular, so they span the entire plane. 

## Thm 

If A is $n$x$n$ symmetric with eigenvalues $\lambda_1, \lambda_2,... \lambda_n$ and corresponding eigenvectors (orthogonalized & normalized) $x_1, x_2,... x_n$, then A can be expressed as
$$
A = CDC^T, 
$$
where 
$$
C = 
\begin{bmatrix} 
x_1 & x_2 & \cdots & x_n 
\end{bmatrix}
$$
is an orthogonal (w/ eigenvectors) and 
$$
D = 
\begin{bmatrix} 
\lambda_1 \\
 & \lambda_2 \\
 & & \ddots \\
 & & & \lambda_n 
\end{bmatrix}
$$
is diagonal (w/ eigenvalues). This is called spectral decomposition (or eigendecomposition). 

## Corollary 

If A is symmetric and C and D are defined as before, then 
$$
C^TAC = D <=> A = CDC^T.
$$

This is called diagonalization. 

e.g. 
$$
A = 
\begin{bmatrix} 
2 & 0 \\
0 & 3
\end{bmatrix}
$$
and 
$$
x = 
\begin{bmatrix} 
x_1 \\
x_2
\end{bmatrix}, 
$$
then what this transformation does is that it doubles $x_1$ and triples $x_2$. 

Say, for example, $x = \begin{bmatrix} 0.5, 1.5 \end{bmatrix}$. In order to quantify it, we set bases to be $\begin{bmatrix} 0, 1 \end{bmatrix}$ and $\begin{bmatrix} 1, 0 \end{bmatrix}$ to construct x and y axes. In general, choices of bases are arbitrary: 

$C^T b$ 

$DC^T b$ gets matrix amplification 

$DC^T b$ gets to the new system 

$CDC^T b$ transforms it back. 

Note. Double check geometric of spectral decomposition.  

## Thm 

If A is $n$x$n$ with eigenvalues $\lambda_1, \lambda_2,... \lambda_n$, then 

i) $det(A) = \lambda_1 \lambda_2 ... \lambda_n$

ii) $trace(A) = \lambda_1 + \lambda_2 ... + \lambda_n$

Proof. HW. Assume A is symmetric and then use spectral decomposition. In general, A does not need to be symmetric. 

Remark. 

i) A is singular $<=>$ $det(A) = 0$ $<=>$ at least one $\lambda_i = 0$ since Thm i) 

ii) $rank(A) =$ # of nonzero $\lambda_i$ 

In general, $A = CDC^T$ and check $D$. 

Proof. $A = CDC^T$ where $C$ is orthogonal, then 
$$
rank(A) = rank(CDC^T) \\
= rank(D)
$$
since $*$ orthogonal does not change rank

$$
= rank(\begin{bmatrix} 
\lambda_1 \\
 & \lambda_2 \\
 & & \ddots \\
 & & & \lambda_n 
\end{bmatrix}) \\
$$

$=$ # of nonzero $\lambda_i$ 

e.g. 
$$
A = 
\begin{bmatrix} 
1 & 2 \\
-1 & 4
\end{bmatrix}
$$
with $\lambda_1 = 3$, $\lambda_2 = 2$. Vertify that 

i) $det(A) = 1 x 4 - 2 x (-1) = 6 = 3 x 2 = \lambda_1 \lambda_2$ 

ii) $tr(A) = 1 + 4 = 5 = 3 + 2 = \lambda_1 + \lambda_2$

## Thm 

Let A be $n$x$n$ symmetric with eigenvalues $\lambda_1, \lambda_2,... \lambda_n$, 

i) A is pd $<=>$ $\lambda_i > 0$ $\forall i$

ii) A is psd $<=>$ $\lambda_i \geq 0$ $\forall i$

Proof. HW. 

i) makes sense. Full rank. 

ii) Consider $A^{1/2}$, if A is psd, then $A = CDC^T$ where $D$ is diagonal with $\lambda_i \geq 0$. Define 
$$
A^{1/2} = CD^{1/2}C, 
$$
where
$$
D = 
\begin{bmatrix} 
\lambda_1^{1/2} \\
 & \lambda_2^{1/2} \\
 & & \ddots \\
 & & & \lambda_n^{1/2} 
\end{bmatrix}
$$

Ques. Why does it make sense to take $D^{1/2}$? 
$$
A^{1/2} A^{1/2} = (CD^{1/2}C^T) (CD^{1/2}C^T) \\
= CD^{1/2} I D^{1/2} C^T \\
= CD^{1/2} D^{1/2} C^T \\
= CD C^T = A
$$

$A$ is $n$x$n$, $x \in \mathbb{R}^n$ $A: \mathbb{R}^n \rightarrow \mathbb{R}^n$ for $x \rightarrow Ax$ 

For some $A$, the mapping projects any vector $x$ into a linear subspace of $\mathbb{R}^n$. 

e.g. For $n = 2$ 
$$
A = 
\begin{bmatrix} 
\frac{1}{2} & \frac{1}{2} \\
\frac{1}{2} & \frac{1}{2}
\end{bmatrix}
$$
$$
x = 
\begin{bmatrix} 
x_1 \\
x_2
\end{bmatrix}, 
$$
$$
Ax =
\begin{bmatrix} 
\frac{1}{2} & \frac{1}{2} \\
\frac{1}{2} & \frac{1}{2}
\end{bmatrix} 
\begin{bmatrix} 
x_1 \\
x_2
\end{bmatrix} =
\begin{bmatrix} 
\frac{x_1 + x_2}{2} \\
\frac{x_1 + x_2}{2}
\end{bmatrix} 
$$
$A$ is a projection matrix that projects $x$ to the subspace $x_1 = x_2$. 

Ques. Any restriction? 

We need $A^2x = Ax$ $\forall x$. Therefore, we need $A^2 = A$ in order for A to be a projection. (In general, $A^n= A$.) This is also why A is also called idempotent matrix. 

## Def

A is a square matrix and A is said to be idempotent if $A^2 = A$. 

Observation. If A is nonsingular and idempotent, then $A = I$. We will focus on idempotent matrices that are also symmetric. This class of matrices are easy to deal with because of the decomposition. 

## Thm 

If A is symmetric and idempotent, then A is psd. 

Proof.
$$
A = A^2 = AA^T, 
$$
so A is psd. 

If A is symmetric, then A can be written as $A = CDC^T$. 

A is idempotent $<=>$ $A^2 = A$ 
$$
<=> (CDC^T)(CDC^T) = CDC^T
$$
$$
<=> CD^2C^T = CDC^T
$$
$$
<=> D^2 = D
$$

Noice that if $C$ is nonsingular, then $C^T$ is nonsingular.

Recall that 
$$
D = 
\begin{bmatrix} 
\lambda_1 \\
 & \lambda_2 \\
 & & \ddots \\
 & & & \lambda_n
\end{bmatrix}
$$
$$
<=> \begin{bmatrix} 
\lambda_1^2 \\
 & \lambda_2^2 \\
 & & \ddots \\
 & & & \lambda_n^2
\end{bmatrix} = 
\begin{bmatrix} 
\lambda_1 \\
 & \lambda_2 \\
 & & \ddots \\
 & & & \lambda_n
\end{bmatrix}
$$
$$
<=> \lambda_i^2 = \lambda_i \ \ \ \ \ \forall i = 1, 2,... n
$$
$$
<=> \lambda_i = 0 \ or \ 1 \ \ \ \ \ \forall i = 1, 2,... n
$$

## Thm 

If A is $n$x$n$ symmetric, idempotent, and of $rank(A) = r \leq n$, then A has $r$ eigenvalues $= 1$ and $(n - r)$ eigenvalues $= 0$.

Remark. $tr(A) = r = \sum_{i=1}^n \lambda_i$ 

e.g. before 

$$
Ax =
\begin{bmatrix} 
\frac{1}{2} & \frac{1}{2} \\
\frac{1}{2} & \frac{1}{2}
\end{bmatrix} 
\begin{bmatrix} 
x_1 \\
x_2
\end{bmatrix} 
$$

A is 2D, but $rank(A) = 1$. Dimension of subspace has $rank(A) = 1$, which is a line $x_1 = x_2$. I.e. Original x lives in $dim = 2$, $A$ projects $x$ to the subspace $x_1 = x_2$. Some information may be lost. However, we can find a perpendicular subspace $Bx$ that perserves the information. Here, 
$$
x = Ax + Bx.
$$
$x$ can be projcted to two subspaces $Ax$ and $Bx$. Suppose we know $Ax$, then $Bx$ is easy to recover since 
$$
Bx = x - Ax = (I - A) x \ \ \ \ \ \forall x
$$
$$
<=> B = I - A
$$
can also be shown to be idempotent. 

## Thm 

If A is $n$x$n$ idempotent, 

i) $(I - A)$ is also idempotent. (Projection into the complementary space.) 

Proof. Verify that ${(I - A)}^2 = I - A$ and use A is idempotent. 

ii) $A (I - A) = A - A^2 = 0$ or $(I - A) A = 0$

Idea. Once we project to $Ax$, is there anything that is in $Ax$ that is informative? No.

iii) If P is $n$x$n$ nonsingular, then $P^{-1}AP$ is idempotent. 

iv) If C is orthogonal, then $C^TAC$ is idempotent. 

## Summary 

Suppose A is $n$x$n$, P is $n$x$n$ nonsingular, and C is $n$x$n$ orthogonal and let $P^{-1}AP$ be similarity transformation and $C^TAC$ be conjugate transformation, then list of properties include: 

\newpage

\begin{table}[]
\begin{tabular}{|l|l|l|l|}
 & $P^{-1}AP$ & $C^TAC$ \\
rank & yes & yes \\
determinant & yes & yes \\ 
trace & yes & yes \\ 
eigenvalue & yes & yes \\ 
eigenvector & no & no \\ 
symmetric & no & yes \\ 
pd/psd or not & N/A & yes \\ 
idempotent & yes & yes
\end{tabular}
\end{table}


